/*
 * generated by Xtext
 */
package com.joeymink.norm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NormRuntimeModule extends com.joeymink.norm.AbstractNormRuntimeModule {

}
