/*
* generated by Xtext
*/
package com.joeymink.norm.ui.contentassist;

import com.joeymink.norm.ui.contentassist.AbstractNormProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class NormProposalProvider extends AbstractNormProposalProvider {

}
