/*
 * generated by Xtext
 */
package com.joeymink.norm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class NormUiModule extends com.joeymink.norm.ui.AbstractNormUiModule {
	public NormUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
